server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /app {
    rewrite ^ /app/ break;
    rewrite ^/app/(.*)$ /$1 break;
    try_files $uri $uri/ /index.html;
  }

  location /app/assets/ {
    rewrite ^/app/(.*)$ /$1 break;
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location /app/ {
    rewrite ^/app/(.*)$ /$1 break;
    try_files $uri $uri/ /index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
