server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /admin {
    rewrite ^ /admin/ break;
    rewrite ^/admin/(.*)$ /$1 break;
    try_files $uri $uri/ /index.html;
  }

  location /admin/assets/ {
    rewrite ^/admin/(.*)$ /$1 break;
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location /admin/ {
    rewrite ^/admin/(.*)$ /$1 break;
    try_files $uri $uri/ /index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
